import { Injectable } from '@angular/core';
import { Tipoauto } from './tipi/tipi.data';



@Injectable({
  providedIn: 'root'
})
export class AutoService {
  private _autoDisponibili:Tipoauto[]=[
    {marca:"Lamborghini",modello:"Urus",potenza:650,immagine:"../../assets/image/urus.jpeg",prezzo:880,porte:5,autoid:0 ,disponibile:true ,descrizione:"Lamborghini Urus è il primo Super Sport Utility Vehicle al mondo, creato per coniugare l'anima di una supersportiva con le funzionalità pratiche di un SUV. Grazie al suo motore Lamborghini V8 biturbo da 4,0 litri, Urus riunisce in sé divertimento alla guida e capacità davvero sbalorditive, per un concept all'insegna delle prestazioni. Design, performance, dinamica di guida ed emozioni che non conoscono limiti confluiscono armoniosamente in questa visionaria incarnazione del più autentico DNA Lamborghini."},
    {marca:"Lamborghini",modello:"Aventador SVJ",potenza:770,immagine:"../../assets/image/svj.jpeg",prezzo:1230,porte:5,autoid:1,disponibile:true,descrizione:"Lamborghini sa perfettamente come affrontare le sfide, e per questo ha creato Aventador SVJ. Per fondere una tecnologia all’avanguardia con un design eccezionale, senza mai scendere a compromessi. Se in un futuro guidato dalla tecnologia si stanno perdendo le emozioni reali, nel futuro che stiamo disegnando sono sempre al centro, perché alla guida c’è sempre l’uomo."},
    {marca:"Lamborghini",modello:"Huracan Performante",potenza:640,immagine:"../../assets/image/performante.jpeg",prezzo:1050,porte:5,autoid:2,disponibile:true,descrizione:"Huracán Performante ridefinisce il concetto di supersportiva ed eleva le performance a livelli mai visti prima. La vettura è stata interamente riprogettata intervenendo sul peso, sulla potenza del motore, sul telaio e soprattutto introducendo un innovativo sistema di aerodinamica attiva: ALA. L'utilizzo del Forged Composites®, un materiale plasmabile in fibra di carbonio brevettato da Automobili Lamborghini, è un tocco di classe e contribuisce a rendere il veicolo ancora più leggero."},
    {marca:"McLaren",modello:"P1",potenza:916,immagine:"../../assets/image/p1.jpeg",prezzo:2200,porte:5,autoid:3,disponibile:true,descrizione:"Dotata di un’evoluzione del 3.8 biturbo della 12C, la P1 è la prima McLaren stradale ibrida, con un sistema derivato dalla Formula 1 con un motore elettrico da 180 CV, il sistema Kers e il DRS, con in più una batteria ricaricabile da 4,7 kWh che le consente di percorrere una decina di km a zero emissioni. La McLaren P1 ha dimostrato al mondo che McLaren fa sul serio, ed è stata lanciata insieme alle altre Hypercar del 2013, uno degli anni più prolifici della storia dell’auto: Ferrari LaFerrari e Porsche 918 Hybrid."},
    {marca:"McLaren",modello:"Senna",potenza:800,immagine:"../../assets/image/senna.jpeg",prezzo:1940,porte:5,autoid:4,disponibile:false,descrizione:"L'auto è l'ultima novità della McLaren Ultimate Series, che unisce la filosofia progettuale e costruttiva dei modelli F1 e P1, senza essere tuttavia l’erede diretta di queste due vetture. La sua esistenza è stata svelata online, dalla casa costruttrice, il 10 dicembre 2017. La presentazione ufficiale dell'auto ha avuto luogo, poco dopo, al Salone dell'automobile di Ginevra del 2018. Tutti gli esemplari di quest'auto sono costruiti artigianalmente presso il McLaren Production Center di Woking, nel Surrey, in Inghilterra, con una produzione limitata a 500 unità complessive. Il nome dell'auto è dedicato al pilota brasiliano tre volte campione del mondo di Formula 1 Ayrton Senna. Le prestazioni dichiarate dalla casa sono di un tempo di accelerazione da 0 a 100 km/h in 2,8 s ed una velocità massima di 340 km/h"},
    {marca:"Ferrari",modello:"488 pista",potenza:720,immagine:"../../assets/image/488pista.jpeg",prezzo:1100,porte:5,autoid:5,disponibile:false,descrizione:"La Ferrari 488 Pista è equipaggiata con il motore V8 più potente nella storia della Casa di Maranello e porta su un’auto stradale il più alto livello di transfer tecnologico dal mondo delle competizioni, come del resto è testimoniato dal nome, un diretto omaggio alla storia incomparabile della Ferrari in questo campo. La Ferrari 488 Pista trasferisce su strada l’esperienza maturata sui tracciati di tutto il mondo dalla 488 Challenge e dalla 488 GTE."},
    {marca:"Ferrari",modello:"Purosangue",potenza:725,immagine:"../../assets/image/purosangue.jpeg",prezzo:900,porte:5,autoid:6,disponibile:true,descrizione:"A Maranello sono orgogliosi di sottolineare che non hanno messo un super motore su un’auto che era già un SUV, hanno invece costruito attorno al loro motore V12 un’auto più grande, più versatile, più pratica delle altre Ferrari. Sono parole che potrebbero anche far pensare a una di quelle frasi di circostanza usate quando viene presentata una nuova auto; l’anima della Ferrari Purosangue, però, è riassunta bene dalla considerazione di cui sopra."},
    {marca:"Ferrari",modello:"812 Superfast",potenza:800,immagine:"../../assets/image/superfast.jpeg",prezzo:1500,porte:5,autoid:7,disponibile:true,descrizione:"La prima sfida da affrontare per Ferrari, quando si accinge a presentare un nuovo modello, è la più difficile: superare ogni volta se stessa. Questo “challenge” è ancora più impegnativo quando si tratta di impostare la progettazione della nuova 12 cilindri, il motore che segnò l’inizio della gloriosa storia del Cavallino Rampante nel 1947, settant’anni fa. La ricerca e lo sviluppo volti a sfruttare tutto il know-how derivato dalle competizioni hanno dato vita alla 812 Superfast, destinata a offrire sia le migliori performance in assoluto sia la guidabilità più coinvolgente e appagante possibile. Con i suoi 800 CV, 60 in più rispetto alla F12berlinetta, la 812 Superfast diventa la Ferrari stradale più potente e prestazionale di sempre (ad eccezione ovviamente delle serie speciali in serie limitata che montano però il V12 posteriore). La 812 Superfast apre dunque una nuova era nella storia delle 12 cilindri di Maranello, forte dell’eredità preziosa ricevuta dalle F12berlinetta ed F12tdf. Per sfruttare nel migliore dei modi tutta la potenza e bilanciare perfettamente i pesi è progettata attorno ad una architettura transaxle estremamente evoluta, che prevede il motore anteriore abbinato al cambio in posizione posteriore."},
    {marca:"Pagani",modello:"Huayra",potenza:850,immagine:"../../assets/image/huayra.jpeg",prezzo:3200,porte:5,autoid:8,disponibile:false,descrizione:"Lo studio della Huayra è iniziato nel 2003, quando la concorrenza rischiava di far invecchiare precocemente la Zonda (il cui progetto risaliva ai primi anni novanta). L'obiettivo era quindi quello di realizzare una vettura completamente nuova, che rappresentasse la massima espressione tecnologica del mondo automobilistico. Gli otto anni necessari a completare la Huayra sono stati utilizzati per studiare e perfezionare le numerose soluzioni tecniche che nel frattempo erano state utilizzate sulle vetture della famiglia Zonda: una su tutte, il telaio al carbotanio. Anche dal punto di vista estetico il percorso è stato estremamente lungo. Si è infatti partiti da un centinaio di bozzetti per arrivare, dopo numerose ricerche e soluzioni scartate, alla linea definitiva."},
    {marca:"Pagani",modello:"Zonda S",potenza:408,immagine:"../../assets/image/zondas.jpeg",prezzo:2500,porte:5,autoid:9,disponibile:true,descrizione:"Vista da fuori, Zonda S ha un design aggressivo e imponente seguito da un suono feroce, ma dentro tutto si evolve. Solo quando la schiena sarà appoggiata sul sedile in carbonio e le mani avranno impugnato il volante ed ingranato la prima marcia, la percezione verrà catapultata e sorpresa in un comfort inaspettato, grazie alla silenziosità del motore Mercedes-AMG, alla luminosità della cupola, all’ottima insonorizzazione e alla quasi totale assenza di vibrazioni, nonostante il peso di 1250 kg. Zonda S è reattiva in ogni condizione, estremamente precisa nella guida, priva di rollio e beccheggio."},
  ]

  constructor() { }

  cercaAuto(autoid:number){
    return this._autoDisponibili.find(a => a.autoid == autoid)
  }

  setNonDisponibile(autoid:number){
    for (let i = 0; i<this._autoDisponibili.length; i++){
      if(autoid === this._autoDisponibili[i].autoid){
        this._autoDisponibili[i].disponibile=false
      }
    }
  }

  get autoDisponibili(){
    return [... this._autoDisponibili]
  }
}
